### ISSUE TITLE
Version constraints

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPSimulators.jl#17]
Shouldn't the current version (0.3.0) have `POMDPs` v0.8 as a lower bound because it want's to use the `DDNStructucture` type which does not exist in v0.7.3?

**Comment by MaximeBouton** [comment]
POMDPs v0.7.3 does export `DDNStructure` I think.

**Comment by lassepe** [comment]
Oh never mind. I got this wrong. I was looking at the master, not v0.7.3. Thank you @MaximeBouton!

**Comment by MaximeBouton** [comment]
Actually, why is v0.7.3 not merged to master? @zsunberg

**Comment by zsunberg** [comment]
I thought it made more sense to have v0.8 merge into master and any future
0.7 releases come from the version-0.7 branch. The commits for version
0.7.3 branch away from the version 0.8 commits, so there would be a weird
merge if we merged 0.7.3 into master before 0.8. I thought 0.8 seemed more
like the trunk.

**Comment by MaximeBouton** [comment]
Ok I did not realize there would be more 0.7.3 versions but I think it makes sense.
