### ISSUE TITLE
`stepthrough` spec default broken (?)

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPSimulators.jl#18]
I think the default value of `spec` is not in scope [here](https://github.com/JuliaPOMDP/POMDPSimulators.jl/blob/master/src/stepthrough.jl#L171) (also in the other versions of `stepthrough`). This breaks in the `POMDPModels` unit tests. Maybe we can add a test here.

**Comment by zsunberg** [comment]
Ok, I'll fix it!

**Comment by zsunberg** [comment]
thanks!
