### ISSUE TITLE
Sim() with initialstate as a Distribution in QuickPOMDPs

### ISSUE THREAD

**Issue by bkraske** [JuliaPOMDP/POMDPSimulators.jl#39]
It seems that when defining an initial state as a distribution (in this case a deterministic distribution) within a QuickPOMDPs MDP, the initial state is not recognized when the MDP is used in a Sim() object.
If the initial state is not a distribution, Sim() is able to be ran (using run() ). If the HistoryRecorder() is used directly, an initial state as a distribution also runs.

**Comment by zsunberg** [comment]
Thanks for reporting, @bkraske ! I think i fixed it!
