### ISSUE TITLE
`DisplaySimulator` to work with Pluto notebooks

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/POMDPSimulators.jl#49]
Pluto requires the output to be the renderable object, which is different than Jupyter and Electron.

**Comment by zsunberg** [comment]
Hmmm... So are you thinking that we should make `simulate(::DisplaySimulator, ...)` return some kind of Gif-like object? How will it know *not* to call `display` at every timestep?

Does this do what you need? https://github.com/JuliaPOMDP/POMDPGifs.jl

**Comment by mossr** [comment]
I think I jumped the gun with this issue—I already get around this problem in Pluto using a `HistoryRecorder` and then just rendering each step like so:
![image](https://user-images.githubusercontent.com/1592413/133892262-6ad39477-9424-4ecc-9628-96c4d5eddb82.png)

POMDPGifs works well too as an alternative. So I'll close this as it looks like the intended purpose of the `DisplaySimulator` is to pop out a separate window (which works well in Jupyter/Electron settings, but doesn't fit well in Pluto).
