### ISSUE TITLE
make SimHistory an AbstractVector{NamedTuple} and implement the abstract vector interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPSimulators.jl#8]
Right now it's kinda hard to access all the information in a history. This would make it easier.

**Comment by zsunberg** [comment]
cc: @lassepe

**Comment by lassepe** [comment]
Would you then want to get rid of the `HistoryIterator`?

**Comment by zsunberg** [comment]
Maybe... I think `eachstep` might still be useful. We would at least need to keep it around for a while because a lot of code uses it.

**Comment by zsunberg** [comment]
finished this
